class JudgeProcedureController < ApplicationController
  def all_questions
    render :json => TF_QUESTIONS
  end
TF_QUESTIONS = [
{:number=>1, :answer=>'T', :question=>'A competition organizer may serve as the judge director and may also serve as a judge, provided this person has no knowledge of the association between entries and entrants. (Note: The competition organizer may NOT receive judging experience points if they serve as judge.)'},
{:number=>2, :answer=>'T', :question=>'A judge director may serve as a judge, provided this person has no knowledge of the association between entries and entrants.'},
{:number=>3, :answer=>'T', :question=>'A competition organizer may serve as the judge director, provided this person has no knowledge of the association between the association between entries and entrants.'},
{:number=>4, :answer=>'F', :question=>'A judge director may not serve as a judge, even if this person has no knowledge of the association between entries and entrants.'},
{:number=>5, :answer=>'F', :question=>'A competition organizer may not serve as a judge, even if this person has no knowledge of the association between entries and entrants.'},
{:number=>6, :answer=>'T', :question=>'A judge director may serve as the competition organizer and may also serve as a judge, provided this person has no knowledge of the association between entries and entrants.'},
{:number=>7, :answer=>'T', :question=>'If an individual has knowledge of the association between entries and entrants they may not serve as a judge.'},
{:number=>8, :answer=>'T', :question=>'A competition organizer may serve as a judge, provided this person does not divulge information about entries and entrants to other judges.'},
{:number=>9, :answer=>'T', :question=>'The "head" judge at a table should try to tutor apprentice or lower-rank judges if time permits.'},
{:number=>10, :answer=>'F', :question=>'The steward at the table has sole responsibility for completing the Cover Sheets for beers in each flight.'},
{:number=>11, :answer=>'T', :question=>'The "head" judge at the table has sole responsibility for completing the Cover Sheets for beers in each flight.'},
{:number=>12, :answer=>'T', :question=>'The "head" judge at a table should fill out Cover Sheets for beers in his or her flight as directed by the competition management.'},
{:number=>13, :answer=>'F', :question=>'The "head" judge at a table has no responsibility for filling out Cover Sheets for beers in his or her flight as directed by the competition management.'},
{:number=>14, :answer=>'T', :question=>'The "head" judge at the table has sole responsibility for completing the Cover Sheets for beers in each flight but with the agreement of the steward may delegate the completion of the Cover Sheets to the steward.'},
{:number=>15, :answer=>'T', :question=>'The "head" judge, with the agreement of the steward, may delegate filling in of the Cover Sheets for beers in his or her flight to the steward.'},
{:number=>16, :answer=>'F', :question=>'There is no need for the "head" judge to complete the Flight Summary Sheet - the competition organizer can obtain all that information from the cover sheets.'},
{:number=>17, :answer=>'T', :question=>'If possible, there should be at least one BJCP-ranked judge in every flight.'},
{:number=>18, :answer=>'T', :question=>'When novice judges evaluate entries in a competition, each novice should be paired with a BJCP judge.'},
{:number=>19, :answer=>'T', :question=>'Novice judges may only evaluate entries if authorized by the judge director, and novices should be paired with BJCP judges when possible.'},
{:number=>20, :answer=>'T', :question=>'To reduce stray odors and flavors present, beverages and foods other than water, bread or crackers should not be brought to the judging table.'},
{:number=>21, :answer=>'F', :question=>'It is acceptable to bring food items other than bread, crackers, and water to the judging table.'},
{:number=>22, :answer=>'F', :question=>'You must filter out strong scents from fellow judges or the environment from your mind rather than discussing the problem with the competition organizer.'},
{:number=>23, :answer=>'T', :question=>'Strong scents from the environment or other judges or stewards should be brought to the attention of the competition organizer.'},
{:number=>24, :answer=>'F', :question=>'Because entries cannot have any identifying marks, it is OK for a judge to judge beers in a category he or she has entered.'},
{:number=>25, :answer=>'T', :question=>'If a judge is assigned to judge a category that he/she has entered, that judge should ask the competition organizer to reassign him/her to another category.'},
{:number=>26, :answer=>'F', :question=>'If assigned to judge a category that he or she has entered a judge should just judge the category without notifying the judge director or competition organizer.'},
{:number=>27, :answer=>'F', :question=>'Judges should not review the sub-style being judged from the BJCP Style Guidelines while at the judging table prior to judging that style.'},
{:number=>28, :answer=>'T', :question=>"Judges may invite stewards to taste the beers in a flight, if there's enough sample to share."},
{:number=>29, :answer=>'T', :question=>'It is acceptable to change the order in which you judge the beers on your flight sheet from how it was printed.'},
{:number=>30, :answer=>'F', :question=>'Beers must be evaluated in the sequence specified on the flight sheet.'},
{:number=>31, :answer=>'F', :question=>'If you have eaten spicy or greasy food within a few hours prior to judging, you should use mouthwash or antiseptic rinse before judging.'},
{:number=>32, :answer=>'T', :question=>'You should avoid eating spicy or greasy food within a few hours prior to judging.'},
{:number=>33, :answer=>'T', :question=>"Spicy and/or hot foods should be avoided prior to a judging event because they can reduce a judge's sensitivity to the aromas and flavors of beer."},
{:number=>34, :answer=>'T', :question=>"Perfumed shampoos and colognes should be avoided prior to a judging event because they can reduce a judge's sensitivity to the aromas of beer."},
{:number=>35, :answer=>'F', :question=>'It is a good idea to take a decongestant prior to a judging event to increase your sensitivity to the aromas of beer.'},
{:number=>36, :answer=>'F', :question=>'Calibrations beers are selected to be the standard against which entries should be judged.'},
{:number=>37, :answer=>'T', :question=>'It is the responsibility of the "head" judge, in consultation with the other judges in a flight, to assign a consensus score to each entry.'},
{:number=>38, :answer=>'F', :question=>'It is not necessary for scores produced by the judges on a panel to be within seven points or each other.'},
{:number=>39, :answer=>'T', :question=>'After discussing the initial scores, judges should adjust their final scores to be within seven points.'},
{:number=>40, :answer=>'T', :question=>'Judges must adjust their scores to be within seven points (or less if directed by the competition director) of each other as part of developing a consensus score for the beer.'},
{:number=>41, :answer=>'T', :question=>'The consensus score assigned to the beer is not necessarily an average score.'},
{:number=>42, :answer=>'T', :question=>'It is important to be quick as well as to write your scoresheets thoroughly and completely.'},
{:number=>43, :answer=>'T', :question=>'On average, experienced judges should be able to completely evaluate a beer, including arriving at a consensus, in 10 minutes.'},
{:number=>44, :answer=>'F', :question=>'When there is a discrepancy in the scores for a given beer, the lower-ranked judges should yield to the opinion of the highest ranked BJCP judge at the table.'},
{:number=>45, :answer=>'T', :question=>'It is acceptable to remove offensive smelling entries from the judging table after they have been evaluated.'},
{:number=>46, :answer=>'F', :question=>'A judge must disqualify an entry if it has raised lettering or the cap has identifying marks.'},
{:number=>47, :answer=>'F', :question=>'A judge may disqualify an entry if it has an improper bottle or cap.'},
{:number=>48, :answer=>'T', :question=>'Only the judge director or competition organizer can disqualify an entry.'},
{:number=>49, :answer=>'T', :question=>'The results of the bottle inspection does not affect the scoring.'},
{:number=>50, :answer=>'T', :question=>'Snide or rude comments are unacceptable on scoresheets.'},
{:number=>51, :answer=>'T', :question=>'Pour each entry in a manner that gives it its optimum appearance, keeping in mind that some entries may be over- or under-carbonated.'},
{:number=>52, :answer=>'F', :question=>'When you suspect an entry has been placed in the wrong flight based on the style being judged, you should request that it be judged in a different flight instead.'},
{:number=>53, :answer=>'T', :question=>'When you suspect an entry has been placed in the wrong flight based on the style being judged, you should consult with the judge director or competition organizer.'},
{:number=>54, :answer=>'T', :question=>'Sniff the entry immediately after pouring to ensure proper evaluation of volatile aromatics.'},
{:number=>55, :answer=>'F', :question=>'There is no need to sniff the aroma immediately after pouring the entry into the glass.'},
{:number=>56, :answer=>'T', :question=>'Complete judging of one entry before moving on to the next entry.'},
{:number=>57, :answer=>'F', :question=>'It is not necessary to offer any feedback for improvement if you score a beer above 40.'},
{:number=>58, :answer=>'T', :question=>'It is common practice to refrain from sharing your thoughts while judging a beer until the other judges have completed their scoresheet.'},
{:number=>59, :answer=>'F', :question=>'If you are very familiar with a beer style, it is preferable to disregard the BJCP Style Guidelines and rely on your personal expertise instead.'},
{:number=>60, :answer=>'F', :question=>"If rushed, it's OK to write only comments and an overall score on a scoresheet, leaving the scores for the subsections blank."},
{:number=>61, :answer=>'F', :question=>"If rushed, it's OK to write only 1-2 comments on a scoresheet as long as the numeric score is filled out."},
{:number=>62, :answer=>'F', :question=>'If a beer is a "gusher" or has an unpleasant aroma upon opening, a judge may assign a courtesy score of 13 without tasting and commenting on the characteristics of the beer.'},
{:number=>63, :answer=>'T', :question=>'All beers should be tasted and scored, even if they are "gushers" or have an unpleasant aroma upon opening.'},
{:number=>64, :answer=>'F', :question=>'It is appropriate to penalize the entrant if the beer is not served at the proper temperature.'},
{:number=>65, :answer=>'T', :question=>'If the beers are not served at the proper temperature work with the competition staff to resolve the problem.'},
{:number=>66, :answer=>'F', :question=>'In each section of a scoresheet, you should only comment upon the most prominent features of each entry, not subtle characteristics.'},
{:number=>67, :answer=>'F', :question=>"Judges' comments must not include phrases like \"if you used ..\""},
{:number=>68, :answer=>'F', :question=>"Judges' comments must not include phrases like \"did you ..\""},
{:number=>69, :answer=>'T', :question=>"Judges' comments must include a complete evaluation of the sensory aspects of the entry and how those aspects relate to the style guidelines."},
{:number=>70, :answer=>'T', :question=>"Judges' comments should be constructive and reflect knowledge of the brewing, fermentation, bottling, and handling process."},
{:number=>71, :answer=>'T', :question=>"Judges' comments need to provide information on how to improve the entry as warranted."},
{:number=>72, :answer=>'T', :question=>"Scores should not be assigned to the aroma section immediately because the entry's aroma profile may change over time."},
{:number=>73, :answer=>'F', :question=>'Each section must be scored with a number prior to writing any comments, to best capture your first impressions.'},
{:number=>74, :answer=>'F', :question=>'To assure objectivity, you should never write your full name or put contact information on the scoresheet.'},
{:number=>75, :answer=>'T', :question=>'You should write your full name and judging rank on each scoresheet.'},
{:number=>76, :answer=>'T', :question=>'You should always fill out the "Style Scales" on the scoresheet, as a good check against your scores.'},
{:number=>77, :answer=>'F', :question=>'You should use the "Overall Impression" section of the scoresheet to refer to how the entry compares to other entries in the flight.'},
{:number=>78, :answer=>'T', :question=>'You should use the "Overall Impression" section of the scoresheet to comment on how much you enjoyed the entry or provide suggestions for how to improve the beer.'},
{:number=>79, :answer=>'T', :question=>'A score in the "Outstanding" range is reserved for beers that not only lack flaws but also have the hard-to-define "extraordinary" character that great beers have.'},
{:number=>80, :answer=>'F', :question=>'The courteous lower limit for scores assigned to "Problematic" beers is 6 points-one point for each section of the scoresheet.'},
{:number=>81, :answer=>'T', :question=>'The courteous lower limit for scores assigned to "Problematic" beers is 13 points.'},
{:number=>82, :answer=>'F', :question=>'If judges require more pours than one bottle to judge an entry, the "head" judge should ask the steward to request a second bottle from the cellar master. (Note: The emphasis here is on learning to judge a beer with just a few ounces in your glass. Obviously, for a gusher you would request a second bottle if it was available but you should not ask for an additional bottle just because you are pouring too much.)'},
{:number=>83, :answer=>'F', :question=>'It is preferable to use ink on scoresheets so that your scores and comments cannot be altered by contest personnel.'},
{:number=>84, :answer=>'T', :question=>'It is preferable to use mechanical pencils, rather than wooden pencils, on scoresheets so that wood odors do not interfere with beer aromas.'},
{:number=>85, :answer=>'T', :question=>'It is acceptable to request a second bottle to give the entry a fair chance at an accurate judging if a beer is a "gusher" or tastes infected.'},
{:number=>86, :answer=>'T', :question=>'Entrants may contact the judge, the competition director, or their BJCP Regional Representative if they are dissatisfied with any aspect of their scoresheets.'},
{:number=>87, :answer=>'T', :question=>'When your flight has finished, you should avoid having conversations that might distract other judges who have not yet finished their flights.'},
{:number=>88, :answer=>'F', :question=>'When your flight has finished, it is OK to visit other flights still in progress to see how beers you have entered are faring.'},
{:number=>89, :answer=>'T', :question=>'Because it may have been entered by a person in the room, it is polite to refrain from publicly deriding a "problem" beer that you have scored during a competition.'},
{:number=>90, :answer=>'T', :question=>'Judges from outside the table should not be consulted on a beer unless the judges at the table cannot reach a consensus score, and then only if they all agree to the consultation.'}]
end
